project:
  type: website
  resources:
    - CNAME

website:
  description: "Advanced analysis of public data"
  site-url: https://edisonlmg.github.io/datopediablog/
  google-analytics: "G-Y4LXHS8LXT"
  title: "datopediablog"
  navbar:
    right:
      - about.qmd
      - text: "Dashboards"
        href: dashboards.qmd
      - text: "Presentaciones"
        href: presentations.qmd

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    code-fold: true
    code-copy: true
    code-tools: true
    highlight-style: github

editor: visual

